#!/usr/bin/env python3
"""
Plot chunk_rank timelines from staging_timeline.xlsx into one PNG.

Reads the workbook generated by tools/staging_log_to_excel.py.
Uses elapsed_s columns so midnight crossings are handled correctly.
"""

from __future__ import annotations

import argparse
import math
import zipfile
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from xml.etree import ElementTree as ET

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

NS = {
    "main": "http://schemas.openxmlformats.org/spreadsheetml/2006/main",
    "rel": "http://schemas.openxmlformats.org/officeDocument/2006/relationships",
    "pkgrel": "http://schemas.openxmlformats.org/package/2006/relationships",
}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot chunk_rank sheet from staging timeline workbook."
    )
    parser.add_argument("--xlsx", required=True, help="Path to staging_timeline.xlsx")
    parser.add_argument("--output", "-o", help="Output PNG path.")
    parser.add_argument(
        "--bin-seconds", type=float, default=30.0,
        help="Time bin size in seconds. Default: 30",
    )
    parser.add_argument(
        "--rolling", type=int, default=5,
        help="Rolling average window (number of bins). Default: 5",
    )
    return parser.parse_args()


# ── xlsx reader ──────────────────────────────────────────────────────

def load_sheet_rows(xlsx_path: Path, sheet_name: str) -> List[Dict[str, object]]:
    with zipfile.ZipFile(xlsx_path) as zf:
        workbook = ET.fromstring(zf.read("xl/workbook.xml"))
        rels = ET.fromstring(zf.read("xl/_rels/workbook.xml.rels"))
        rid_to_target = {}
        for rel in rels.findall("pkgrel:Relationship", NS):
            rid_to_target[rel.attrib["Id"]] = rel.attrib["Target"]
        target = None
        for sheet in workbook.findall("main:sheets/main:sheet", NS):
            if sheet.attrib.get("name") == sheet_name:
                rid = sheet.attrib.get(f"{{{NS['rel']}}}id")
                target = rid_to_target.get(rid)
                break
        if target is None:
            raise ValueError(f"sheet not found: {sheet_name}")
        sheet_xml = ET.fromstring(zf.read(f"xl/{target}"))
        return _parse_sheet(sheet_xml)


def _parse_sheet(root: ET.Element) -> List[Dict[str, object]]:
    rows = root.findall("main:sheetData/main:row", NS)
    if not rows:
        return []
    header = _parse_row(rows[0])
    records = []
    for row in rows[1:]:
        values = _parse_row(row)
        if not any(v != "" for v in values):
            continue
        item = {}
        for idx, key in enumerate(header):
            item[key] = _convert(values[idx]) if idx < len(values) else ""
        records.append(item)
    return records


def _parse_row(row_elem: ET.Element) -> List[str]:
    by_idx: Dict[int, str] = {}
    mx = -1
    for cell in row_elem.findall("main:c", NS):
        ci = _col_idx(cell.attrib.get("r", ""))
        ct = cell.attrib.get("t")
        txt = (
            cell.findtext("main:is/main:t", default="", namespaces=NS)
            if ct == "inlineStr"
            else cell.findtext("main:v", default="", namespaces=NS)
        )
        by_idx[ci] = txt
        mx = max(mx, ci)
    return [by_idx.get(i, "") for i in range(mx + 1)] if mx >= 0 else []


def _col_idx(ref: str) -> int:
    letters = "".join(c for c in ref if c.isalpha())
    idx = 0
    for c in letters:
        idx = idx * 26 + (ord(c.upper()) - ord("A") + 1)
    return max(idx - 1, 0)


def _convert(v: str):
    if v == "":
        return ""
    try:
        if "." in v or "e" in v.lower():
            n = float(v)
            return int(n) if n.is_integer() else n
        return int(v)
    except ValueError:
        return v


# ── helpers ──────────────────────────────────────────────────────────

def to_float(v) -> Optional[float]:
    if v in (None, ""):
        return None
    return float(v)


def format_elapsed(s: float) -> str:
    s = max(0.0, s)
    m, s2 = divmod(int(s), 60)
    h, m2 = divmod(m, 60)
    return f"{h:02d}:{m2:02d}:{s2:02d}"


def build_bins(lo: float, hi: float, step: float) -> np.ndarray:
    if hi <= lo:
        hi = lo + step
    start = math.floor(lo / step) * step
    end = math.ceil(hi / step) * step + step
    return np.arange(start, end, step)


def rolling_avg(arr: np.ndarray, window: int) -> np.ndarray:
    if window <= 1 or len(arr) == 0:
        return arr.astype(float)
    kernel = np.ones(window) / window
    return np.convolve(arr, kernel, mode="same")


def build_palette(rounds: List[int]) -> Dict[int, Tuple]:
    cmap = plt.get_cmap("tab20")
    return {rnd: cmap(i % cmap.N) for i, rnd in enumerate(sorted(rounds))}


# ── bin counting ─────────────────────────────────────────────────────

def hist_counts(records, key, bins):
    vals = [to_float(r.get(key)) for r in records]
    vals = [v for v in vals if v is not None]
    if not vals:
        return np.zeros(len(bins) - 1)
    return np.histogram(vals, bins=bins)[0].astype(float)


def hist_by_round(records, time_key, round_key, bins):
    groups: Dict[int, List[float]] = defaultdict(list)
    for r in records:
        t = to_float(r.get(time_key))
        rnd = r.get(round_key)
        if t is None or rnd in (None, ""):
            continue
        groups[int(rnd)].append(t)
    result = {}
    for rnd, vals in groups.items():
        result[rnd] = np.histogram(vals, bins=bins)[0].astype(float)
    return result


# ── plotting ─────────────────────────────────────────────────────────

def make_xticks(bins, step=8):
    x = 0.5 * (bins[:-1] + bins[1:])
    tick_step = max(1, len(x) // step)
    positions = x[::tick_step]
    labels = [format_elapsed(v) for v in positions]
    return positions, labels


def plot_wait_line(ax, records, bins, palette, window, label_prefix=""):
    by_round = hist_by_round(records, "wait_start_elapsed_s", "max_need_round", bins)
    x = 0.5 * (bins[:-1] + bins[1:])
    total = np.zeros(len(bins) - 1)
    for rnd in sorted(by_round):
        smoothed = rolling_avg(by_round[rnd], window)
        ax.fill_between(x, 0, smoothed, alpha=0.15, color=palette.get(rnd))
        ax.plot(x, smoothed, linewidth=1.0, color=palette.get(rnd), label=f"r{rnd}")
        total += by_round[rnd]
    smoothed_total = rolling_avg(total, window)
    ax.plot(x, smoothed_total, linewidth=2.0, color="black", label="total", zorder=10)
    n = sum(1 for r in records if r.get("wait_start_elapsed_s") not in ("", None))
    ax.set_title(f"{label_prefix}waits (n={n})", fontsize=10)
    ax.set_ylabel("chunks / bin")
    ax.grid(alpha=0.2)
    ax.legend(loc="upper right", fontsize=6, ncol=4, title="round")


def plot_send_line(ax, records, bins, window, label_prefix=""):
    counts = hist_counts(records, "send_elapsed_s", bins)
    x = 0.5 * (bins[:-1] + bins[1:])
    smoothed = rolling_avg(counts, window)
    ax.fill_between(x, 0, smoothed, alpha=0.15, color="#4C78A8")
    ax.plot(x, smoothed, linewidth=1.5, color="#4C78A8")
    n = sum(1 for r in records if r.get("send_elapsed_s") not in ("", None))
    ax.set_title(f"{label_prefix}transfers (n={n})", fontsize=10)
    ax.set_ylabel("chunks / bin")
    ax.grid(alpha=0.2)


def plot_scatter(ax, records, palette, label_prefix=""):
    pts = [
        r for r in records
        if r.get("send_elapsed_s") not in ("", None)
        and r.get("max_waiting_seconds") not in ("", None)
    ]
    if not pts:
        ax.set_title(f"{label_prefix}wait duration (no data)", fontsize=10)
        ax.grid(alpha=0.2)
        return
    for rnd in sorted({int(r["max_need_round"]) for r in pts if r.get("max_need_round") not in ("", None)}):
        xs = [to_float(r["send_elapsed_s"]) for r in pts if r.get("max_need_round") not in ("", None) and int(r["max_need_round"]) == rnd]
        ys = [float(r["max_waiting_seconds"]) for r in pts if r.get("max_need_round") not in ("", None) and int(r["max_need_round"]) == rnd]
        ax.scatter(xs, ys, s=14, alpha=0.7, color=palette.get(rnd), label=f"r{rnd}")
    ax.set_title(f"{label_prefix}wait duration (n={len(pts)})", fontsize=10)
    ax.set_ylabel("seconds")
    ax.grid(alpha=0.2)
    ax.legend(loc="upper left", fontsize=6, ncol=4, title="round")


def set_shared_x(axes_row, bins):
    pos, labels = make_xticks(bins)
    for ax in axes_row:
        ax.set_xlim(bins[0], bins[-1])
        ax.set_xticks(pos)
        ax.set_xticklabels(labels, rotation=30, ha="right", fontsize=7)


# ── main ─────────────────────────────────────────────────────────────

def main():
    args = parse_args()
    xlsx_path = Path(args.xlsx)
    output_path = (
        Path(args.output) if args.output
        else xlsx_path.with_name(f"{xlsx_path.stem}_chunk_rank.png")
    )

    rows = load_sheet_rows(xlsx_path, "chunk_rank")
    valid = [r for r in rows if r.get("prefill_tp") not in ("", None)]
    if not valid:
        raise SystemExit("chunk_rank has no prefill_tp rows")

    all_t = []
    for r in valid:
        for k in ("wait_start_elapsed_s", "wait_end_elapsed_s", "send_elapsed_s"):
            v = to_float(r.get(k))
            if v is not None:
                all_t.append(v)
    if not all_t:
        raise SystemExit("no plottable time values")

    bins = build_bins(min(all_t), max(all_t), args.bin_seconds)
    rounds = sorted({int(r["max_need_round"]) for r in valid if r.get("max_need_round") not in ("", None)})
    palette = build_palette(rounds)
    window = args.rolling

    rank_to_rows: Dict[int, list] = defaultdict(list)
    for r in valid:
        rank_to_rows[int(r["prefill_tp"])].append(r)
    ranks = sorted(rank_to_rows)

    has_wait = {
        rank: any(r.get("wait_start_elapsed_s") not in ("", None) for r in rank_to_rows[rank])
        for rank in ranks
    }
    plot_ranks = [rank for rank in ranks if has_wait[rank]]

    num_rows = 1 + len(plot_ranks) + (1 if len(ranks) > len(plot_ranks) else 0)
    fig, axes = plt.subplots(
        num_rows, 3,
        figsize=(26, 4.2 * num_rows),
        constrained_layout=True,
    )
    if num_rows == 1:
        axes = [axes]

    row_idx = 0
    ax_row = axes[row_idx]
    plot_wait_line(ax_row[0], valid, bins, palette, window, "ALL TP: ")
    plot_send_line(ax_row[1], valid, bins, window, "ALL TP: ")
    plot_scatter(ax_row[2], valid, palette, "ALL TP: ")
    set_shared_x(ax_row, bins)
    row_idx += 1

    for rank in plot_ranks:
        ax_row = axes[row_idx]
        prefix = f"tp={rank}: "
        plot_wait_line(ax_row[0], rank_to_rows[rank], bins, palette, window, prefix)
        plot_send_line(ax_row[1], rank_to_rows[rank], bins, window, prefix)
        plot_scatter(ax_row[2], rank_to_rows[rank], palette, prefix)
        set_shared_x(ax_row, bins)
        row_idx += 1

    no_wait_ranks = [rank for rank in ranks if not has_wait[rank]]
    if no_wait_ranks:
        ax_row = axes[row_idx]
        combined = []
        for rank in no_wait_ranks:
            combined.extend(rank_to_rows[rank])
        prefix = f"tp={','.join(str(r) for r in no_wait_ranks)} (no waits): "
        ax_row[0].text(
            0.5, 0.5, "no wait events for these ranks",
            transform=ax_row[0].transAxes, ha="center", va="center", fontsize=12, color="gray",
        )
        ax_row[0].set_title(f"{prefix}waits", fontsize=10)
        plot_send_line(ax_row[1], combined, bins, window, prefix)
        plot_scatter(ax_row[2], combined, palette, prefix)
        set_shared_x(ax_row, bins)

    fig.suptitle(
        f"chunk_rank overview: {xlsx_path.name} | bin={args.bin_seconds:g}s  rolling={window}",
        fontsize=14,
    )
    fig.savefig(output_path, dpi=150)
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
